version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/MyMoney/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/MyMoney/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    groups:
      dependencies:
        dependency-type: "lockfile"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/MyMoney.Core/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/MyMoney.Core/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    groups:
      dependencies:
        dependency-type: "lockfile"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/MyMoney.Tests/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/MyMoney.Tests/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    groups:
      dependencies:
        dependency-type: "lockfile"
    labels:
      - "dependencies"
